# Generated by Django 5.2.8 on 2026-06-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectprofile',
            name='passport',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
