# Generated by Django 5.2.8 on 2026-07-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_alter_prospectprofile_criminal_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectprofile',
            name='current_field',
            field=models.CharField(blank=True, help_text='Filière SOUHAITÉE en Chine (Informatique, Commerce, Médecine) [Q3]', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prospectprofile',
            name='education_level',
            field=models.CharField(blank=True, help_text="Niveau d'études ACTUEL (Bac, Licence, Master) [Q4]", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prospectprofile',
            name='target_program',
            field=models.CharField(blank=True, help_text="Niveau d'études SOUHAITÉ en Chine (Licence, Master, Doctorat, Année de langue) [Q2]", max_length=100, null=True),
        ),
    ]
