# Generated by Django 6.0.5 on 2026-08-16 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('conversations', '0007_alter_prospectprofile_current_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='prospect',
            field=models.ForeignKey(blank=True, help_text='Prospect ayant envoyé ce document (passeport, casier, diplôme, photo...)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='conversations.prospectprofile'),
        ),
    ]
