# Generated by Django 5.2.8 on 2026-06-24 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, help_text='Niveau actuel (lycée, bac, licence, master...)', max_length=100, null=True)),
                ('current_field', models.CharField(blank=True, help_text="Filière actuelle de l'étudiant (ex: sciences, commerce...)", max_length=100, null=True)),
                ('target_program', models.CharField(blank=True, help_text="Programme souhaité à l'étranger (ex: informatique, médecine...)", max_length=100, null=True)),
                ('passport', models.BooleanField(default=False)),
                ('criminal_record', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('cold', 'Froid'), ('warm', 'Moyen'), ('hot', 'Chaud')], default='cold', max_length=20)),
                ('ai_score', models.IntegerField(default=0)),
                ('human_takeover', models.BooleanField(default=False)),
                ('dossier_complet', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_followup', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='conversations.prospectprofile')),
            ],
        ),
    ]
