# Generated by Django 5.2.8 on 2026-06-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_alter_prospectprofile_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectprofile',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='current_step',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='last_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='last_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prospectprofile',
            name='budget',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospectprofile',
            name='current_field',
            field=models.CharField(blank=True, help_text='Ex: sciences, commerce, informatique...', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prospectprofile',
            name='education_level',
            field=models.CharField(blank=True, help_text='Ex: lycée, bac, licence, master...', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prospectprofile',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prospectprofile',
            name='target_program',
            field=models.CharField(blank=True, help_text="Programme souhaité à l'étranger", max_length=100, null=True),
        ),
    ]
