# Generated by Django 5.2.8 on 2026-06-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_prospectprofile_confidence_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectprofile',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
