# Generated by Django 5.2.8 on 2026-07-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_alter_prospectprofile_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectprofile',
            name='departure_date',
            field=models.CharField(blank=True, help_text='Septembre 2026, Mars 2027, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='in_whatsapp_group',
            field=models.CharField(blank=True, help_text='Oui ou Non', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='objective',
            field=models.CharField(blank=True, help_text='Immigrer en Chine ou uniquement étudier', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prospectprofile',
            name='criminal_record',
            field=models.CharField(blank=True, default='Non spécifié', help_text='Oui (casier judiciaire) ou Non (vierge)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prospectprofile',
            name='passport',
            field=models.CharField(blank=True, help_text="Oui, Non, ou date d'expiration", max_length=20, null=True),
        ),
    ]
