# Generated by Django 5.2.8 on 2026-07-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_prospectprofile_departure_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectprofile',
            name='criminal_record',
            field=models.CharField(blank=True, help_text='Oui (casier judiciaire) ou Non (vierge)', max_length=20, null=True),
        ),
    ]
