"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from dotenv import load_dotenv
import dj_database_url
import os
import sys

# Chemin explicite : la détection automatique de load_dotenv() (basée sur
# la pile d'appels) ne trouve pas de façon fiable config/.env une fois
# passée par le chargeur de settings Django.
load_dotenv(BASE_DIR / "config" / ".env")

# Les logs applicatifs utilisent des emojis (✅, ❌, ⚠️). Sur Windows, la
# console par défaut n'est pas en UTF-8 : un simple print() avec emoji y
# lève UnicodeEncodeError et interrompt le traitement en cours (y compris
# le repli sur l'extracteur léger en cas d'erreur Groq). On force stdout/
# stderr en UTF-8 dès le démarrage pour que ces logs ne cassent jamais.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8", errors="replace")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En production (Render), définir SECRET_KEY dans les variables d'environnement.
# La valeur ci-dessous n'est utilisée qu'en local si rien n'est défini.
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-9v0%gwjxxw7^ij5v7o$+*62n0mtc40@90n5%wxksy^z9rr4(e_",
)

# SECURITY WARNING: don't run with debug turned on in production!
# En local (pas de DEBUG dans .env) : True. En production : mettre DEBUG=False
# dans les variables d'environnement de l'hébergeur.
DEBUG = os.getenv("DEBUG", "True").strip().lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".ngrok-free.app",
    ".ngrok-free.dev",
    ".onrender.com",
]


# Application definition

INSTALLED_APPS = [
    'dashboard',
    'rest_framework',

    'accounts',
    'conversations',
    'ai_engine',
    'whatsapp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# En production (Render...), DATABASE_URL est fourni automatiquement par
# l'add-on Postgres. En local, on retombe sur la config Postgres locale
# (identifiants lus depuis config/.env, jamais codés en dur ici).
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "leprof_ai_db"),
            "USER": os.getenv("DB_USER", "postgres"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Fichiers uploadés (documents/photos envoyés par les prospects via WhatsApp)
# ⚠️ Sur un hébergeur gratuit type Render, le disque n'est PAS persistant :
# ces fichiers sont perdus à chaque redéploiement/redémarrage. Acceptable
# pour un test, mais prévoir un stockage externe (S3, Cloudinary...) avant
# une mise en production réelle.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'